[data]

    [data.DEMAND_TMETRO]
    link = "https://zenodo.org/record/1227121/files/TMETRO_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_TCAR]
    link = "https://zenodo.org/record/1227121/files/TCAR_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_TBUS]
    link = "https://zenodo.org/record/1227121/files/TBUS_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_STRAFFIC]
    link = "https://zenodo.org/record/1227121/files/STRAFFIC_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_SPSQUARE]
    link = "https://zenodo.org/record/1227121/files/SPSQUARE_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_SCAFE]
    link = "https://zenodo.org/record/1227121/files/SCAFE_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_PSTATION]
    link = "https://zenodo.org/record/1227121/files/PSTATION_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_PRESTO]
    link = "https://zenodo.org/record/1227121/files/PRESTO_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_PCAFETER]
    link = "https://zenodo.org/record/1227121/files/PCAFETER_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_OOFFICE]
    link = "https://zenodo.org/record/1227121/files/OOFFICE_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_OMEETING]
    link = "https://zenodo.org/record/1227121/files/OMEETING_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_OHALLWAY]
    link = "https://zenodo.org/record/1227121/files/OHALLWAY_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_NRIVER]
    link = "https://zenodo.org/record/1227121/files/NRIVER_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_NPARK]
    link = "https://zenodo.org/record/1227121/files/NPARK_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_NFIELD]
    link = "https://zenodo.org/record/1227121/files/NFIELD_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_DWASHING]
    link = "https://zenodo.org/record/1227121/files/DWASHING_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_DLIVING]
    link = "https://zenodo.org/record/1227121/files/DLIVING_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.DEMAND_DKITCHEN]
    link = "https://zenodo.org/record/1227121/files/DKITCHEN_48k.zip"
    type = "http"
    out-path = "DEMAND"
    file-type = "zip"

    [data.LIBRISPEECH]
    link = "http://www.openslr.org/resources/12/train-clean-100.tar.gz"
    type = "http"
    out-path = "LIBRISPEECH"
    file-type = "tar"

    [data.VCTK]
    link = "http://datashare.is.ed.ac.uk/download/DS_10283_2651.zip"
    type = "http"
    out-path = "VCTK"
    file-type = "zip"
